### ISSUE TITLE
Unable to find OpenVPN3

### ISSUE THREAD

**Issue by krzyska1** [jkotra/eOVPN#29]
I've switched eOVPN settings to OpenVPN3, and now every time I run it I get the message "Unable to find OpenVPN3", I can click Exit, that's it.
How can I restore default settings?

**Comment by jkotra** [comment]
did you install openvpn3? ( [Ubuntu](https://openvpn.net/cloud-docs/openvpn-3-client-for-linux/) / [Fedora](https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/) / [Arch](https://aur.archlinux.org/packages/openvpn3) )

otherwise, if you installed it via Flatpak:
`flaptak uninstall eovpn --delete-data`
and install it again.

**Comment by jkotra** [comment]
this behavior has been fixed in `1.18` (https://github.com/jkotra/eOVPN/commit/1ace2b87d934a74bef83be233856756f3c093b6c). Thanks for reporting.
